MACHINE="spacesom-8mplus-cb"
require conf/machine/spacesom-8mplus-cb.conf

require conf/machine/include/ubuntubasics.inc

PREFERRED_PROVIDER_virtual/kernel = "linux-imx"
PREFERRED_VERSION_virtual/kernel = "6.6.52"

MACHINE_EXTRA_RRECOMMENDS:remove = "linux-firmware-murata-1zm"
