MACHINE="titansbc-8mmini"
require conf/machine/titansbc-8mmini.conf

require conf/machine/include/ubuntubasics.inc

PREFERRED_PROVIDER_virtual/kernel = "linux-imx"
PREFERRED_VERSION_virtual/kernel = "6.6.52"
