MACHINE="visionsom-8mm-cb"
require conf/machine/visionsom-8mm-cb.conf

require conf/machine/include/ubuntubasics.inc

PREFERRED_PROVIDER_virtual/kernel = "linux-imx"
PREFERRED_VERSION_virtual/kernel = "6.6.52"

